"""materialized stats

Revision ID: db5ae3dfce17
Revises: 0001_initial_schema
Create Date: 2026-04-28 19:49:44.852946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_materialized_stats'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_snapshots',
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('total_input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_moves', sa.BigInteger(), nullable=True),
    sa.Column('cost_input_total', sa.Float(), nullable=True),
    sa.Column('cost_output_total', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('model_name')
    )
    op.create_index(op.f('ix_leaderboard_snapshots_model_name'), 'leaderboard_snapshots', ['model_name'], unique=False)
    op.create_table('matrix_cells',
    sa.Column('player_a', sa.String(), nullable=False),
    sa.Column('player_b', sa.String(), nullable=False),
    sa.Column('wins_a', sa.Integer(), nullable=True),
    sa.Column('wins_b', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('player_a', 'player_b')
    )
    op.create_index(op.f('ix_matrix_cells_player_a'), 'matrix_cells', ['player_a'], unique=False)
    op.create_index(op.f('ix_matrix_cells_player_b'), 'matrix_cells', ['player_b'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matrix_cells_player_b'), table_name='matrix_cells')
    op.drop_index(op.f('ix_matrix_cells_player_a'), table_name='matrix_cells')
    op.drop_table('matrix_cells')
    op.drop_index(op.f('ix_leaderboard_snapshots_model_name'), table_name='leaderboard_snapshots')
    op.drop_table('leaderboard_snapshots')
    # ### end Alembic commands ###
